### ISSUE TITLE
BadTranslator IP rotation

### ISSUE THREAD

**Issue by Jacherr** [Jacherr/assyst-tracking#10]
At the moment, the BadTranslator API relies on a single IP for all requests. If the IP is banned, then the API must be redeployed *manually* in order to get a new IP. This can be fixed by using IP rotation so that the API does not hammer the translation service with a single IP, which should hopefully mitigate some of the 'too many attempts' errors that are appearing more frequently recently.

**Comment by y21** [comment]
BT API now detects said failures and falls back to other IPs/nodes.
