### ISSUE TITLE
commands should still use images from message_reference (if there is any) when the message is edited

### ISSUE THREAD

**Issue by arcy-at** [Jacherr/assyst-tracking#17]

**Comment by Jacherr** [comment]
This should happen, not sure why it doesn't work right now

**Comment by y21** [comment]
`message_reference` is not sent when a message is updated, so the command handler doesn't see the message reference. This probably requires caching messages to work properly.
> Unlike creates, message updates may contain only a subset of the full message object payload (but will always contain an id and channel_id).
