### ISSUE TITLE
suggestion: more basic image manipulation commands

### ISSUE THREAD

**Issue by HighArcs** [Jacherr/assyst-tracking#18]
all of these are stolen from photoshop lol

[hue shifting](https://arcs.loves.catboys.space/PUVENIE8Ar.png), [posterize](https://arcs.loves.catboys.space/MXy38nrIRs.png), vibrance & [saturation](https://arcs.loves.catboys.space/DgV2AsaR1A.png), [lightness](https://arcs.loves.catboys.space/MXv8pAqF8N.png), [exposure](https://arcs.loves.catboys.space/FOgS6FxNV6.png), [adding noise](https://arcs.loves.catboys.space/SilMYTK7ZL.png), [sharpen](https://arcs.loves.catboys.space/4QLMFemVr3.png), [solarize](https://arcs.loves.catboys.space/_X6cYmP0SV.png), [diffuse](https://arcs.loves.catboys.space/ywDMYOilJ3.png), [extrude](https://arcs.loves.catboys.space/OqBYBzCkQ9.png), find edges, [wind](https://arcs.loves.catboys.space/2YHdymO8VU.png), [pinch](https://arcs.loves.catboys.space/xkc3ZuDaSy.png), [crystallize](https://arcs.loves.catboys.space/hZHWb8eybd.png), [twirl](https://arcs.loves.catboys.space/8EQEDVX2Dx.png)

**Comment by Jacherr** [comment]
I would like to keep the amount of 'least significance' commands like this at a minimum, mainly because they won't be popular and will probably add a lot of extra maintenance work, but I could add basic things like sharpening. Some of these filters are unrealistic to achieve with image-rs right now.

**Comment by Jacherr** [comment]
All of these things can probably eventually be done via tags now instead.
