### ISSUE TITLE
Some command suggestions

### ISSUE THREAD

**Issue by Diamondtroller** [Jacherr/assyst-tracking#21]
`-remind remove [index]`
maybe alias `-reminder` for `remind` too
`-3dspin` make image spin around it's vertical and horizontal axis

**Comment by piotrek117studos** [comment]
image commands wil be added: -curcuitboard, -mirror left right up and down and -bobross

**Comment by Jacherr** [comment]
- [x] `remind remove` 
- [x] `reminder` alias
- [ ] 3d spin
