### ISSUE TITLE
-enlarge doesn't work on stickers

### ISSUE THREAD

**Issue by Diamondtroller** [Jacherr/assyst-tracking#24]
I don't know if api supports it or not, but would be cool if enlarge could work on stickers.

**Comment by Jacherr** [comment]
I can look into adding this for stickers that exist as APNG/PNG/GIF. I haven't found a way to decode [lottie](https://github.com/airbnb/lottie) stickers as a raster format yet, if anyone finds a way please leave a comment.

**Comment by Jacherr** [comment]
This functionality was added in the last couple of deployments.
