### ISSUE TITLE
add eval command

### ISSUE THREAD

**Issue by webtax-gh** [Jacherr/assyst-tracking#26]
Hello!

please add an eval command that all users can use

the command should run whatever the input is in the shell the bot is hosted on

the token should be easily accessible and we should be able to do whatever we want

the command should be `-eval` or `-sh`

also can you remove germany from -overlay, thanks

Thanks,
WebTax

**Comment by Jacherr** [comment]
1. this command already exists, try it
2. i will not betray my homie y21 like that

**Comment by webtax-gh** [comment]
oh lol thanks

also can you remove germany from -overlay, thanks

**Comment by Jacherr** [comment]
i will not betray my homie y21 like that

**Comment by webtax-gh** [comment]
please

**Comment by Jacherr** [comment]
i cant
i mustnt

**Comment by bup0441** [comment]
make y21 overlay and remove germany
then you haven't betrayed the homie but you've satisfied web hacks

**Comment by y21** [comment]
yes

**Comment by bup0441** [comment]
glad we agree
