### ISSUE TITLE
Assyst on hold

### ISSUE THREAD

**Issue by Jacherr** [Jacherr/assyst-tracking#35]
Over the last few months, my motivation to work on Assyst and other related projects has pretty much fallen flat. I can't work on it for very long without feeling boredom and resentment; I've been tinkering with it for over two years now.

To that end, I'm putting Assyst in a state of 'self-maintenance' for the time being. I'll still host and manage it in case it goes down, but I'm not interested in implementing new features or fixing any bugs that aren't critical at this time

**Comment by y21** [comment]
I'm still up for working on implementing features and commands for Assyst.
