### ISSUE TITLE
Option to excluded filters used in -badcommand

### ISSUE THREAD

**Issue by Diamondtroller** [Jacherr/assyst-tracking#36]
Add a way of excluding some filters for `-badcommand`.

One way this could be achieved using flag parser:
`-badcommand [image] -exclude "[command1] [command2] [command3]"`
For example `-badcommand -exclude "card"` wouldn't use `-card` as any of `-badcommand`'s filters.

**Comment by y21** [comment]
Thanks, this was added in the last commit
