### ISSUE TITLE
Assyst will assyst on pinned messages

### ISSUE THREAD

**Issue by stemount** [Jacherr/assyst-tracking#37]
## Steps to Reproduce
Not sure if this is a feature or a bug (its fairly low priority). Assyst will actually react to messages you pin that have any of the `-flag, -motivate, -whatever` cmds.

### Unrelated Notes
Explanation about the broken manosphere not related to issue

![CleanShot 2021-12-28 at 19 47 20@2x](https://user-images.githubusercontent.com/150512/147601941-8fe7cca9-dd73-45f0-8657-bfb732deaa1f.png)

**Comment by Jacherr** [comment]
That's probably a by-product of the bot not checking the message type before going ahead and parsing the content. I'll make an attempt to fix this now.

**Comment by Jacherr** [comment]
This was fixed in the latest update.
