### ISSUE TITLE
[maybe vip thing but you could watermark it...] make some way of creating a nitro avatar

### ISSUE THREAD

**Issue by stemount** [Jacherr/assyst-tracking#40]
dumb ideas thrown out there as this might not even really be the point of the bot

1. I found an avatar animation thing  on some www.craptastic2000.com that gave me a decent PFP with a nice animation, maybe:
  1. overlaying some pretty decent stream-esque patterns
  1. adding a subtle shake or something
  1. overlaying a sound icon
  1. somehow making an animated server profile banner and pfp...... both animate

more madness in the thread - open to suggestions

**Comment by Jacherr** [comment]
If you could give examples for points 2, 4, and 5, that would be ideal as I'm not too sure what you mean by those.
